### ISSUE TITLE
Proposal for STUN/TURN server configuration

### ISSUE THREAD

**Issue by xieyubo** [wish-wg/webrtc-http-ingest-protocol#91]
## Motivation
In current protocol, there are two ways to return STUN/TURN server configuration to client. One is returning the configuration in OPTIONS request before POST request. The other is returning the configuration in POST request. Both ways have drawbacks.

**The drawback of returning the configuration in OPTIONS request:**
First, in web client, the preflight OPTIONS request is automatically sent and can't be controlled by user's code. If user code explicitly sends OPTIONS request with fetch API, user can't set `Access-Control-Request-Method` and `Access-Control-Request-Headers` headers which are treated as unsafe headers for OPTIONS request. 

Second, OPTIONS request and the following POST request might be routed to different WHIP endpoints by the load balancer. For example, the service provider deploys WHIP endpoints and TURN servers in multiple regions. In order to reduce the latency as much as possible, the service provider wishes the WHIP endpoints in region A use the TURN servers in region A, and WHIP endpoints in region B use the TURN servers in region B. But OPTIONS request might be routed to the region A and the client will get the turn servers in region A, and the following POST request might be routed to the region B. Then user might use WHIP endpoint in region B and TURN server in region A.

**The draw back of returning the configuration in POST request.**
As mentioned in current protocol, some webrtc implementations do not support updating the STUN/TURN server after the local offer has been created. And for the web client, user must trigger an ice-restart processing after updating the STUN/TURN server. So it requires the server support ice restart which is optional feature. Also, ice-restart will introduce unnecessary delay, it's better to avoid it if possible.

## New proposal
In order to avoid the above drawbacks, I proposal a new way to return the STUN/TURN server configuration. It is an optional feature and is compatible with current protocol.

### Protocol Operation
1. Client sends an empty POST request (without SDP offer) to the WHIP endpoint.
2. WHIP endpoint responses the STUN/TURN server configuration in LINK header and **a temporary WHIP resource URL** in Location header.
3. Client sends the POST request (with SDP offer) to the **temporary WHIP resource URL**.
4. The same operations defined in the current protocol.

```
 +-------------+    +---------------+ +--------------+ +---------------+
 | WHIP client |    | WHIP endpoint | | Media Server | | WHIP resource |
 +--+----------+    +---------+-----+ +------+-------+ +--------|------+
    |                         |              |                  |
    |HTTP POST (empty)        |              |                  |
    +------------------------>+              |                  | 
    |201 Created (empty)      |              |                  |
    +<------------------------+              |                  |
    |HTTP POST (SDP Offer)    |              |                  |
    +------------------------>+              |                  |
    |201 Created (SDP answer) |              |                  |
    +<------------------------+              |                  |
    |          ICE REQUEST                   |                  |
    +--------------------------------------->+                  |
    |          ICE RESPONSE                  |                  |
    |<---------------------------------------+                  |
    |          DTLS SETUP                    |                  |
    |<======================================>|                  |
    |          RTP/RTCP FLOW                 |                  |
    +<-------------------------------------->+                  |
    | HTTP DELETE                                               |
    +---------------------------------------------------------->+
    | 200 OK                                                    |
    <-----------------------------------------------------------x
```

The **temporary WHIP resource URL** can be the WHIP endpoint URL or the WHIP resource URL depends on which server can process the following POST request with SDP offer.

In order to be compatible with current protocol, if WHIP endpoint/resource returns STUN/TURN configuration in the second POST request, the configuration **MUST** be the same as the configuration returned in the first POST request.

## Improvement in future
In the future version, we can consider to allow WHIP endpoint returns SDP offer in the first POST, that means the server takes the caller role to send the SDP offer to client, and the client takes the callee role to response the answer back. In this case, we can eliminate the second POST request or use the second POST request for media renegotiate purpose (for example, user want's to turn off video but keep audio on going).

**Comment by murillo128** [comment]
This has been discussed quite a few times in the past, both in the mailing list and in the github issues.

Long story short, all web browsers supports current stun/turn server configuration in the 201 created response without triggering and ice-restart. 

The OPTIONS request is only meant to be used by non-browsers having issues in their webrtc. It was initially introduced due to gstreamer implementation, which has been just fixed and supports updating the stun/turn config received on the response.

**Comment by xieyubo** [comment]
I didn't some research, seems after config ice server via `pc.setConfiguration()`, I must invoke `pc.setLocalDescription()` to gathering the new ice address. But I'm not clear about how can I send these ice address to server? Seems server must support trickle ice/ice restart? But both trickle ice and ice restart are optional. Is there a way to support configing ice server without trickle ice and ice restart on server side.

**Comment by murillo128** [comment]
Please check this for futher info:

https://github.com/wish-wg/webrtc-http-ingest-protocol/issues/66

**Comment by xieyubo** [comment]
Thanks!

But in #66, it seems still doesn't show there is a way to send client ice addresses got from ice server to WHIP endpoint. I still think it's better if there is a way that client can config ice server before posting the offer instead of restricting the server being on a public IP or behind a port forwarding NAT.

**Comment by murillo128** [comment]
> I did some research, seems after config ice server via pc.setConfiguration(), I must invoke pc.setLocalDescription() to gathering the new ice address. But I'm not clear about how can I send these ice address to server? Seems server must support trickle ice/ice restart? But both trickle ice and ice restart are optional. Is there a way to support configing ice server without trickle ice and ice restart on server side.

You can send the new gathered ICE candidates with the PATCH request to the server. Note that the Trickle ICE support on server side is now RECOMMENDED to avoid this kind of issues.

**Comment by murillo128** [comment]
does the RECOMMENDED change address your issue? can we close this?

**Comment by seanturner** [comment]
@xieyubo hoping you could have a look this week as we're trying to make sure we get a new version out under the submission deadline on 20230313. Thanks!

**Comment by xieyubo** [comment]
RECOMMENDED works. I've closed this issue. Thanks!
